org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC -XX:-UseCompressedOops -XX:-UseCompressedClassPointers -Dfile.encoding=UTF-8
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# KSP2 is used by default with KSP 2.2.0-2.0.2
